$script_mysql = <<-SCRIPT
  apt-get update && \
  apt-get install -y mysql-server-5.7 && \
  mysql < /vagrant/mysql/script/user.sql && \
  cat /vagrant/mysql/mysqld.cnf > /etc/mysql/mysql.conf.d/mysqld.cnf && \
  service mysql restart
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/bionic64"
  
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 1024
    vb.cpus = 1
  end

  # *Atenção* Professor como não consegui entender em qual porta 
  #  você tentaria acessar deixei as duas portas liberadas 
  # Exemplo: mysql -h localhost -u root -P 3306 -p
  # ou mysql -h localhost -u root -p

  config.vm.define "mysqlserver8" do |mysqlserver|
    config.vm.network "forwarded_port", guest: 3306, host: 8080, id: 'idPorta'
    config.vm.network "forwarded_port", guest: 3306, host: 3306, id: 'idPortaPrincMysql'

    mysqlserver.vm.provider "virtualbox" do |vb|
      vb.name = "mysqlserver8"
    end

    mysqlserver.vm.provision "shell", inline: $script_mysql
  end
  
end
